const mongoose = require('./connection')
const Character = require('../models/Character')
const Movie = require('../models/Movie')
const Quote = require('../models/Quote')
const characterSeeds = require('./characterSeeds.json')
const movieSeeds = require('./movieSeeds.json')
const quoteSeeds = require('./quoteSeeds.json')
const quoteSeeds2 = require('./quoteSeeds2.json')
const quoteSeeds3 = require('./quoteSeeds3.json')


Movie.deleteMany()
    .then(console.log)
Movie.insertMany(movieSeeds)
    .then(console.log)
    .catch(console.error)

Character.deleteMany()
    .then(console.log)
Character.insertMany(characterSeeds)
    .then(console.log)
    .catch(console.error)

Quote.deleteMany()
    .then(console.log)
Quote.insertMany(quoteSeeds)
    .then(console.log)
    .catch(console.error)
Quote.insertMany(quoteSeeds2) 
    .then(console.log)
    .catch(console.error)
Quote.insertMany(quoteSeeds3)
    .then(console.log)
    .catch(console.error)
    .finally(() => { process.exit() })