const Character = require('../models/Character')
const Movie = require('../models/Movie')
const Quote = require('../models/Quote')
const characterSeeds = require('./characterSeeds.json')
const movieSeeds = require('./movieSeeds.json')
const quoteSeeds = require('./quoteSeeds.json')
const axios = require('axios')

Movie.deleteMany()
    .then(console.log)
Movie.insertMany(movieSeeds)
    .then(console.log)
    .catch(console.error)

Character.deleteMany()
    .then(console.log)
Character.insertMany(characterSeeds)
    .then(console.log)
    .catch(console.error)

Quote.deleteMany()
    .then(console.log)
Quote.insertMany(quoteSeeds)
    .then(console.log)
    .catch(console.error)
        .finally(() => { process.exit() })